<?php
if(!defined('ABSPATH')) exit;
if(!class_exists('Comitement_Site_Observer_V1')){
final class Comitement_Site_Observer_V1{
 const VERSION='1.0.0'; const NS='comitement-observer/v1';
 static function site_id(){return defined('COMITEMENT_OBSERVER_SITE_ID')?(string)COMITEMENT_OBSERVER_SITE_ID:sanitize_key(parse_url(home_url('/'),PHP_URL_HOST));}
 static function site_name(){return defined('COMITEMENT_OBSERVER_SITE_NAME')?(string)COMITEMENT_OBSERVER_SITE_NAME:get_bloginfo('name');}
 static function token(){ $consts=defined('COMITEMENT_OBSERVER_TOKEN_CONSTANTS')?(array)COMITEMENT_OBSERVER_TOKEN_CONSTANTS:[];foreach($consts as$c)if(is_string($c)&&defined($c)&&constant($c))return(string)constant($c);$opts=defined('COMITEMENT_OBSERVER_TOKEN_OPTIONS')?(array)COMITEMENT_OBSERVER_TOKEN_OPTIONS:[];foreach($opts as$o){$v=(string)get_option($o,'');if($v!=='')return$v;}$key='comitement_observer_token_'.self::site_id();$v=(string)get_option($key,'');if($v===''){$v=wp_generate_password(64,false,false);update_option($key,$v,false);}return$v;}
 static function allowed(WP_REST_Request $r){$a=self::token();$b=(string)$r->get_header('x-comitement-site-token');return$a!==''&&$b!==''&&hash_equals($a,$b);}
 static function init(){add_action('rest_api_init',[__CLASS__,'routes']);add_action('admin_menu',[__CLASS__,'menu']);add_action('admin_post_comitement_observer_rotate',[__CLASS__,'rotate']);}
 static function routes(){register_rest_route(self::NS,'/status',['methods'=>'GET','callback'=>[__CLASS__,'status'],'permission_callback'=>[__CLASS__,'allowed']]);}
 static function menu(){add_management_page('Comitement Observer','Comitement Observer','manage_options','comitement-observer',[__CLASS__,'page']);}
 static function rotate(){if(!current_user_can('manage_options'))wp_die('Nicht erlaubt.');check_admin_referer('comitement_observer_rotate');update_option('comitement_observer_token_'.self::site_id(),wp_generate_password(64,false,false),false);wp_safe_redirect(admin_url('tools.php?page=comitement-observer&rotated=1'));exit;}
 static function page(){if(!current_user_can('manage_options'))return;$t=self::token();echo'<div class="wrap"><h1>Comitement Observer</h1><p>Read-only Statusschnittstelle für den privaten Comitement Hub.</p><table class="widefat striped" style="max-width:1000px"><tbody><tr><th>Website</th><td>'.esc_html(self::site_name()).'</td></tr><tr><th>Endpoint</th><td><code>'.esc_html(rest_url(self::NS.'/status')).'</code></td></tr><tr><th>Site Token</th><td><code style="word-break:break-all">'.esc_html($t).'</code></td></tr></tbody></table><p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=comitement_observer_rotate'),'comitement_observer_rotate')).'">Observer-Token rotieren</a></p></div>';}
 static function plugins(){require_once ABSPATH.'wp-admin/includes/plugin.php';$all=get_plugins();$active=(array)get_option('active_plugins',[]);$net=is_multisite()?(array)get_site_option('active_sitewide_plugins',[]):[];$up=get_site_transient('update_plugins');$out=[];foreach($all as$f=>$p){$slug=dirname($f)==='.'?basename($f,'.php'):dirname($f);$out[]=['file'=>$f,'slug'=>$slug,'name'=>(string)($p['Name']??$slug),'version'=>(string)($p['Version']??''),'active'=>in_array($f,$active,true)||isset($net[$f]),'network_active'=>isset($net[$f]),'update_available'=>isset($up->response[$f]),'available_version'=>isset($up->response[$f])?(string)($up->response[$f]->new_version??''):null];}usort($out,fn($a,$b)=>strcasecmp($a['name'],$b['name']));return$out;}
 static function scheduled(){$types=get_post_types(['show_ui'=>true],'names');unset($types['attachment']);$q=new WP_Query(['post_type'=>array_values($types),'post_status'=>'future','posts_per_page'=>50,'orderby'=>'date','order'=>'ASC','no_found_rows'=>true]);$o=[];foreach($q->posts as$p)$o[]=['id'=>(int)$p->ID,'title'=>get_the_title($p),'post_type'=>$p->post_type,'post_type_label'=>get_post_type_object($p->post_type)->labels->singular_name??$p->post_type,'scheduled_local'=>get_post_time('c',false,$p),'scheduled_utc'=>get_post_time('c',true,$p),'edit_url'=>get_edit_post_link($p->ID,'raw'),'url'=>get_permalink($p)];return$o;}
 static function cron(){$arr=function_exists('_get_cron_array')?_get_cron_array():[];$now=time();$due=0;$next=null;foreach((array)$arr as$ts=>$hooks){$ts=(int)$ts;if($next===null||$ts<$next)$next=$ts;if($ts<$now-300)foreach((array)$hooks as$events)foreach((array)$events as$instances)$due+=count((array)$instances);}return['disabled'=>defined('DISABLE_WP_CRON')&&DISABLE_WP_CRON,'overdue_events'=>$due,'next_event_utc'=>$next?gmdate('c',$next):null];}
 static function issues($plugins,$theme,$cron){$o=[];$add=function($c,$s,$m)use(&$o){$o[]=['code'=>$c,'severity'=>$s,'message'=>$m];};if(!is_ssl())$add('https','critical','WordPress erkennt die Anfrage nicht als HTTPS.');if(version_compare(PHP_VERSION,'8.1','<'))$add('php_old','warning','PHP '.PHP_VERSION.' ist veraltet.');$pu=array_values(array_filter($plugins,fn($p)=>!empty($p['update_available'])));if($pu)$add('plugin_updates','warning',count($pu).' Plugin-Update(s) sind verfügbar.');if(!empty($theme['update_available']))$add('theme_update','warning','Für das aktive Theme ist ein Update verfügbar.');if(!empty($cron['disabled']))$add('cron_disabled','warning','WP-Cron ist deaktiviert; externer Cron muss funktionieren.');if(($cron['overdue_events']??0)>0)$add('cron_overdue','warning',$cron['overdue_events'].' Cron-Ereignis(se) sind mehr als fünf Minuten überfällig.');return$o;}
 static function status(){global$wp_version;$plugins=self::plugins();$t=wp_get_theme();$ut=get_site_transient('update_themes');$theme=['slug'=>$t->get_stylesheet(),'name'=>$t->get('Name'),'version'=>$t->get('Version'),'update_available'=>isset($ut->response[$t->get_stylesheet()]),'available_version'=>isset($ut->response[$t->get_stylesheet()])?(string)($ut->response[$t->get_stylesheet()]['new_version']??''):null];$cron=self::cron();$scheduled=self::scheduled();return rest_ensure_response(['ok'=>true,'schema_version'=>1,'observer_version'=>self::VERSION,'generated_at'=>current_time('mysql'),'site'=>['id'=>self::site_id(),'name'=>self::site_name(),'url'=>home_url('/'),'wordpress'=>$wp_version,'php'=>PHP_VERSION,'timezone'=>wp_timezone_string(),'multisite'=>is_multisite()],'theme'=>$theme,'plugins'=>$plugins,'scheduled_posts'=>$scheduled,'cron'=>$cron,'updates'=>['plugins'=>count(array_filter($plugins,fn($p)=>!empty($p['update_available']))),'theme'=>!empty($theme['update_available'])?1:0],'issues'=>self::issues($plugins,$theme,$cron)]);}
}
Comitement_Site_Observer_V1::init();
}
