<?php
// Generated by comitement/scripts/vendor_contentbridge.py; preserve legacy routes.
if(!defined('ABSPATH'))exit;
require_once __DIR__.'/contentbridge-v1.php';
Comitement_ContentBridge_V1::init(function(){
 if(defined('CM91_CONTENT_SECRET')&&constant('CM91_CONTENT_SECRET')!=='')return (string)constant('CM91_CONTENT_SECRET');
 if(defined('CM91_DEPLOY_SECRET')&&constant('CM91_DEPLOY_SECRET')!=='')return (string)constant('CM91_DEPLOY_SECRET');
 $value=(string)get_option('cm91_git_deployer_secret','');if($value!=='')return $value;
 return '';
},['images'=>['_cm91_content_images'],'source'=>['_cm91_content_source_id'],'managed'=>[]]);
